### ISSUE TITLE
Unable to understand the features

### ISSUE THREAD

**Issue by DivyaAgrawal23** [pcbreviglieri/Data-Science-Cropland-Mapping#1]
I have recently started working on this project. I am unable to understand what exactly are the features (i.e. f1, f2, f3 and so on) signify? Can you name some?

**Comment by paulobreviglieri** [comment]
Divya, the following papers, co-authored by Dr. Iman Khosravi (University of Tehran), provide the details you are looking for:

http://i-khosravi.ir/_sources/tres2019.pdf - Section 3.1
http://i-khosravi.ir/_sources/tres2018b.pdf - Section 2.2

Please let me know if this addresses you question, so that I can close this open issue. Thank you!

**Comment by DivyaAgrawal23** [comment]
Hello,
Thanks a lot for your assistance. The links provided by you above are not
accessible. It's showing me "site cannot be reached" when I am clicking on
those. Is there any other way in which I can access those pdfs or if you
can provide me with the downloaded copies it would be much appreciated.
Thanks a lot.

**Comment by paulobreviglieri** [comment]
Links are working just fine for me. I uploaded copies of both papers to the [support](https://github.com/pcbreviglieri/data-science-cropland-mapping/tree/master/support) folder into this repository.

**Comment by DivyaAgrawal23** [comment]
Thank you so much for your help. You can close the issue.

I had a question regarding data augmentation. As crop 2 and 7 have
unbalanced distribution of data as compared to the rest of the data, why
didn't you apply data augmentation there to increase the quantity of data
for those crops?

Thanks and Regards,
Divya

**Comment by paulobreviglieri** [comment]
Thanks, Divya. I am very much interested in understanding how data augmentation could be implemented in this particular case to address the dataset imbalance. Maybe we could push performance metrics up to the 99% range also for these two less represented classes. What would you suggest?

**Comment by DivyaAgrawal23** [comment]
Hi Paulo,
Yes, I believe balance distribution of data is required to get a well
performing model.
Data augmentation for an image usually involves transformation, rotation,
scaling, etc of the input image. *ImageDataGenerator* from keras can be
used to multiply the data for crop 2 and 7. But here the doubt that I have
is, can we really plot these image features? Let me know if you are aware
of any technique which can help me plot the image features to form a
cropland image.
The other alternative approach can be *SMOTE* library which helps in
reducing data imbalance by creating data by taking a dataset as input.

One more area which I am looking forward to exploring is, can we predict
the yield of the crop with the given data? Let me know your thoughts.

Thanks and Regards,
Divya

**Comment by paulobreviglieri** [comment]
Fully agree with your proposal, but the dataset in this case is _**not**_ a set of images. Instead, the dataset is _**tabular**_ - a .txt table with numerical features representing parameters resulting from previous preprocessing of proprietary images and radar-based information, executed by the dataset authors. As we are not dealing with images directly, the techniques you highlight are _**not applicable**_.
Predicting crop yields would, in my opinion, require data collected in a larger set of dates (e.g. once a week, over several weeks), so that the crop growing status could be tracked. We could tentatively investigate not only the size of crops, leaves etc. but also the changes in leaf colors, for example. If such data were available my first answer would be yes, it could be possible. However, the dataset furnished by the University of Tehran team includes data collected on two specific days only (July 5 and 14, 2012), very close to each other. With the current dataset I can't see how to predict yields. But you can contact the dataset authors directly, they may have a different insight. 
Hope to have answered your questions, please confirm.

**Comment by DivyaAgrawal23** [comment]
Thanks a lot for your help. We're currently exploring how different 2&7 are
from others using KNN to determine if we need to resample.

**Comment by pcbreviglieri** [comment]
Closing this issue. Feel free to open a new one should you have further questions. Thanks.

**Comment by paulobreviglieri** [comment]
Closing this issue. Feel free to open a new one should you have further questions. Thanks.

**Comment by DivyaAgrawal23** [comment]
yes sure thanks.
